"""Database models."""
import uuid
from datetime import datetime
from sqlalchemy import Column, String, Integer, Text, DateTime, ForeignKey, JSON, Float
from sqlalchemy.orm import relationship
from .db import Base


def generate_uuid():
    return str(uuid.uuid4())


class User(Base):
    """User model."""
    __tablename__ = "users"

    id = Column(String, primary_key=True, default=generate_uuid)
    name = Column(String(100), nullable=True)
    email = Column(String(255), nullable=True, unique=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    profile = relationship("UserProfile", back_populates="user", uselist=False, cascade="all, delete-orphan")
    files = relationship("UploadedFile", back_populates="user", cascade="all, delete-orphan")
    plans = relationship("Plan", back_populates="user", cascade="all, delete-orphan")
    daily_logs = relationship("DailyLog", back_populates="user", cascade="all, delete-orphan")


class UserProfile(Base):
    """User profile information."""
    __tablename__ = "user_profiles"

    id = Column(String, primary_key=True, default=generate_uuid)
    user_id = Column(String, ForeignKey("users.id"), unique=True, nullable=False)

    # Basic info
    age = Column(Integer, nullable=True)
    education = Column(String(100), nullable=True)
    major = Column(String(200), nullable=True)
    current_job = Column(String(200), nullable=True)
    industry = Column(String(200), nullable=True)

    # Skills (stored as JSON)
    programming_skills = Column(JSON, default=list)
    language_skills = Column(JSON, default=list)
    professional_skills = Column(JSON, default=list)
    work_experience_years = Column(Float, default=0)

    # Interests
    interests = Column(JSON, default=list)

    # Goals
    career_goal = Column(Text, nullable=True)
    income_goal = Column(String(200), nullable=True)
    learning_goal = Column(Text, nullable=True)
    life_goal = Column(Text, nullable=True)

    # Additional notes
    additional_info = Column(Text, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    user = relationship("User", back_populates="profile")


class UploadedFile(Base):
    """Uploaded file metadata."""
    __tablename__ = "uploaded_files"

    id = Column(String, primary_key=True, default=generate_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    filename = Column(String(255), nullable=False)
    original_filename = Column(String(255), nullable=False)
    file_type = Column(String(50), nullable=False)
    file_size = Column(Integer, nullable=False)
    file_path = Column(String(500), nullable=False)
    content_text = Column(Text, nullable=True)  # Extracted text content
    status = Column(String(50), default="pending")  # pending, processed, failed
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="files")


class Plan(Base):
    """Life plan generated by agents."""
    __tablename__ = "plans"

    id = Column(String, primary_key=True, default=generate_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    title = Column(String(200), default="我的未来五年成长规划")
    status = Column(String(50), default="processing")  # processing, completed, failed

    # Final report content (JSON)
    final_report = Column(JSON, nullable=True)

    # Progress tracking
    current_step = Column(String(100), default="starting")
    progress_percent = Column(Integer, default=0)

    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    user = relationship("User", back_populates="plans")
    agent_results = relationship("AgentResult", back_populates="plan", cascade="all, delete-orphan")


class AgentResult(Base):
    """Individual agent analysis results."""
    __tablename__ = "agent_results"

    id = Column(String, primary_key=True, default=generate_uuid)
    plan_id = Column(String, ForeignKey("plans.id"), nullable=False)
    agent_type = Column(String(50), nullable=False)  # career, learning, finance, risk, master
    agent_name = Column(String(100), nullable=False)
    content = Column(Text, nullable=False)  # JSON formatted result
    status = Column(String(50), default="pending")  # pending, processing, completed, failed
    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    plan = relationship("Plan", back_populates="agent_results")


class DailyLog(Base):
    """Daily growth tracking log."""
    __tablename__ = "daily_logs"

    id = Column(String, primary_key=True, default=generate_uuid)
    user_id = Column(String, ForeignKey("users.id"), nullable=False)
    log_date = Column(String(20), nullable=False)  # YYYY-MM-DD

    # Daily activities
    completed_tasks = Column(JSON, default=list)  # List of completed items
    learning_hours = Column(Float, default=0)
    code_lines = Column(Integer, default=0)
    reading_count = Column(Integer, default=0)

    # AI analysis
    ai_analysis = Column(Text, nullable=True)
    suggestions = Column(Text, nullable=True)
    completion_rate = Column(Float, default=0)

    notes = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    user = relationship("User", back_populates="daily_logs")
